### ISSUE TITLE
Please update the golang version in Dockerfile for unit test to 1.11 or above

### ISSUE THREAD

**Issue by saurabhkagrawal** [cloudfoundry/app-autoscaler-ci#6]
Hello Team,

I found out that the latest version of app-autoscaler needs golang version 1.11 or above.
Also there is need to install "gcc" in the image for unit-testing.

Thanks and Regards,
Saurabh Kumar Agrawal

**Comment by qibobo** [comment]
@saurabhkagrawal what is gcc for?

**Comment by saurabhkagrawal** [comment]
I am not sure, but it the tests were not working without gcc. I got specific error regarding gcc being not installed. I will try to find the logs or recreate the error, and share it here.

**Comment by qibobo** [comment]
@saurabhkagrawal 
Thank you for your feedback. The dockerfile and related scripts have been upgraded. I will submit another PR to update the readme document to introduce how to setup the pipeline soon.

**Comment by garethjevans** [comment]
Closing this - golang has been updated to the latest 1.15
